{\rtf1\ansi\ansicpg936\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red24\green26\blue31;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c12157\c13725\c16078;\cssrgb\c100000\c100000\c100000;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 # Netlify \uc0\u36335 \u30001 \u22238 \u36864 \u37197 \u32622 \u65292 \u35299 \u20915  SPA \u23376 \u39029 \u38754 \u21047 \u26032  404\
[[redirects]]\
from = "/*"\
to = "/index.html"\
status = 200\
\
# \uc0\u21487 \u36873 \u65306 \u37197 \u32622 \u32531 \u23384 \u35268 \u21017 \u65292 \u25552 \u21319 \u35775 \u38382 \u36895 \u24230 \u24182 \u38477 \u20302 \u36164 \u28304 \u28040 \u32791 \
[[headers]]\
for = "/*"\
[headers.values]\
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"}